defaults: &defaults
  working_directory: ~/c25k-timer
  docker:
    - image: circleci/node:7.10
  branches:
    ignore:
      - gh-pages

version: 2
jobs:
  build:
    <<: *defaults

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run: yarn test
  deploy:
    <<: *defaults

    steps:
      - add_ssh_keys:
          fingerprints:
            - "44:c6:39:b4:66:4a:09:2a:fd:80:77:24:87:f7:e3:92"

      - checkout
      
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: git config --global user.email "$GH_EMAIL"
      - run: git config --global user.name "$GH_NAME"

      - run: yarn deploy

workflows:
  version: 2

  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
